### ISSUE TITLE
Resampling indices

### ISSUE THREAD

**Issue by hgascon** [Hanjun-Dai/pytorch_structure2vec#12]
Hi @Hanjun-Dai, could you briefly explain the role of the function at 
https://github.com/Hanjun-Dai/pytorch_structure2vec/blob/master/harvard_cep/util.py#L27 ? Thanks.

**Comment by Hanjun-Dai** [comment]
Hello, sorry for my late reply -- this is used for handling the imbalanced data. I'm trying to give samples with different labels equal chance of being sampled. You can also try the weighted loss to help resolve this problem.
