### ISSUE TITLE
Error with make -j4 in Harvard CEP

### ISSUE THREAD

**Issue by FalconLK** [Hanjun-Dai/pytorch_structure2vec#13]
After I installed rdkit, I tried make -j4 in .../pytorch_structure2vec/harvard_cep/ 

I got this error, do you have any idea? 
"""
g++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -Wall -O3 -std=c++11 -I./include -I/.../rdkit/Code -Wno-unused-local-typedef -fPIC -MMD -c -o build/lib/mol_utils.o src/lib/mol_utils.cpp
g++: error: unrecognized command line option '-fno-plt'
Makefile:41: recipe for target 'build/lib/mol_utils.o' failed
make: *** [build/lib/mol_utils.o] Error 1
"""

I've tried 3 different platforms but the same error comes out all the time. 

Thank you ! I'll wait for the answer :)

**Comment by Deadlyelder** [comment]
To further supplement the error, I received the following error

```bash
pytorch_structure2vec/harvard_cep> $ make -j4  
g++ -Wall -O3 -std=c++11 -I./include -I/Users/BLANK/Documents/Github/rdkit/build/Code -Wno-unused-local-typedef -fPIC -MMD -c -o build/lib/mol_utils.o src/lib/mol_utils.cpp
In file included from src/lib/mol_utils.cpp:1:
In file included from ./include/mol_utils.h:5:
/Users/BLANK/Documents/Github/rdkit/build/Code/GraphMol/RingInfo.h:10:10: fatal error: 'RDGeneral/export.h' file not found
#include <RDGeneral/export.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/lib/mol_utils.o] Error 1
```

Thanks

**Comment by FalconLK** [comment]
Issue solved.

_Solution_: Reinstalled system from scratch and install the Boost library from source.
