### ISSUE TITLE
Undefined symbol in libmol.so

### ISSUE THREAD

**Issue by hgascon** [Hanjun-Dai/pytorch_structure2vec#2]
Hi @Hanjun-Dai, I have installed rdkit from source and was able to compile the harvard cep. However, when I try to run the example experiment, loading libmol.so in mol_lib.py line 12:

 ``` 
self.lib = ctypes.CDLL('%s/build/dll/libmol.so' % dir_path)
```
returns an undefined symbol error:
```
OSError: ./build/dll/libmol.so: undefined symbol: _ZN5RDKit17SmilesMolSupplierC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iibb
```
Any hints here? Thanks!

**Comment by Hanjun-Dai** [comment]
Hi there, it seems the error is related to RDKIT, since the function 'SmilesMolSupplier...' belongs to rdkit. 

To make several things clear:
1) which version of rdkit did you use? I used https://github.com/rdkit/rdkit/releases/tag/Release_2017_09_1

2) In the Makefile, the include path is set to $RDBASE/Code, and the lib path is set to $RDBASE/lib
So make sure the lib files are there. 

Let me know if that works.

**Comment by hgascon** [comment]
I used rdkit from the repository. Now I have tried with the Release_2017_09_1 version and it compiles without errors but, then I get the same error when compiling harvard_cep. What version of boost have you used?

**Comment by Hanjun-Dai** [comment]
I was using boost 1.64.0, but I don't think it is due to boost c++.

Also is the error reported during compilation or execution?

**Comment by hgascon** [comment]
Execution

**Comment by hgascon** [comment]
Ok, problem solved. Apparently, as described [here](https://stackoverflow.com/questions/856116/changing-ld-library-path-at-runtime-for-ctypes), ctypes does not use LD_LIBRARY_PATH in linux and the solution is to pass the linker the relative path of the libraries needed:
```
-Wl,-rpath='.',-rpath='./another/relative/rpath'
```

**Comment by Hanjun-Dai** [comment]
That's great! Thanks for investigating into the issue! 

But it seems your linker tells the right path already. I've added -L$RDBASE/lib to the Makefile, it should be able to find the right file. Maybe you can check whether your desired rdkit lib has highest priority in LD_LIBRARY_PATH
