### ISSUE TITLE
Getting the embedding vector for a graph

### ISSUE THREAD

**Issue by vaastav** [Hanjun-Dai/pytorch_structure2vec#21]
I was wondering what are the exact instructions for extracting the embedded vector for a graph from a pre-trained model.
I was able to train a model using my dataset but I am unsure regarding how to use that model. If you could provide some instructions then I'd be really grateful! Thanks

**Comment by Hanjun-Dai** [comment]
see example here:
https://github.com/Hanjun-Dai/pytorch_structure2vec/blob/master/graph_classification/main.py#L62

**Comment by vaastav** [comment]
So embed is the embedded vector? Cool, that makes sense. Thank You!
