### ISSUE TITLE
MacOS compilation

### ISSUE THREAD

**Issue by AntoinePrv** [Hanjun-Dai/pytorch_structure2vec#4]
Hello,

The `Makefile` doesn't work out of the box on MacOS for the simple reason that `find` doesn't have a `printf` option.

I replaced this [line](https://github.com/Hanjun-Dai/pytorch_structure2vec/blob/bf7c270f73a961f07dbe1263fc2355b84cb6cc5f/s2v_lib/Makefile#L12) with
```
cpp_files = $(shell $(FIND) src/lib -name "*.cpp" -print | rev | cut -d"/" -f1 | rev)
```

It seems to do the trick under both MacOS and Linux

**Comment by Hanjun-Dai** [comment]
Nice trick! I've merged it into the repository, thanks!

btw, previously I installed gnu find using homebrew in MaxOS, so I didn't realize this problem.
