### ISSUE TITLE
LoadMolGraph for NetworkX objects

### ISSUE THREAD

**Issue by hgascon** [Hanjun-Dai/pytorch_structure2vec#7]
https://github.com/Hanjun-Dai/pytorch_structure2vec/blob/848db859f471ad010c1465534251d0bf6ac5531c/harvard_cep/mol_lib.py#L74-L111

Is the commented code a working alternative to load NetworkX objects?

**Comment by Hanjun-Dai** [comment]
No, sorry that code was copied from my another project, which is completely meaningless here. 

Sorry for the confusion.
