### ISSUE TITLE
libmol.so: file too short

### ISSUE THREAD

**Issue by caijiangyao1991** [Hanjun-Dai/pytorch_structure2vec#9]
python main.py -gm mean_field -saved_model saved/mean_field.model -phase test -mode cpu
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from mol_lib import MOLLIB, MolGraph
  File "/home/caijiangyao/structure2vec/harvard_cep/mol_lib.py", line 115, in <module>
    MOLLIB = _mol_lib()
  File "/home/caijiangyao/structure2vec/harvard_cep/mol_lib.py", line 12, in __init__
    self.lib = ctypes.CDLL('%s/build/dll/libmol.so' % dir_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/caijiangyao/structure2vec/harvard_cep/build/dll/libmol.so: file too short

**Comment by Hanjun-Dai** [comment]
can you try to clean everything and recompile it?

**Comment by caijiangyao1991** [comment]
@Hanjun-Dai  thanks it works , but i don't have gpu so i still can't run... i have another question,i don't really understand this data structure , just know the last data means the  PCE values
[SiH2]1C=CC=C1c1cc2c3c[nH]cc3c3c4[se]ccc4c4cocc4c3c2o1 2.06

**Comment by Hanjun-Dai** [comment]
Yes the last column corresponds to PCE
